# RETO 5 — El mapa incompleto de los vertederos
## Pesaje de Residuos Sólidos — Santiago de los Caballeros

**Contexto:** El Ayuntamiento Municipal de Santiago de los Caballeros mantiene un registro mensual de pesaje de residuos sólidos recolectados por compañías privadas (COMLURSA, URBALUZ) y brigadas propias (AMS, Mecanizados). El dataset cubre abril 2022 a diciembre 2023 con datos diarios distribuidos en múltiples hojas de un archivo Excel.

**Objetivo:** Realizar una auditoría completa de calidad de datos y preparar el dataset para análisis de minería de datos.

---

## 0. Preparación del Ambiente

In [ ]:
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

sns.set_theme(style='whitegrid', palette='Set2')
pd.set_option('display.max_columns', 20)
pd.set_option('display.float_format', '{:.2f}'.format)
print("Librerías cargadas correctamente")

✅ Librerías cargadas correctamente

## 1. Exploración Inicial del Dataset

### 1.1 Carga y unificación de todas las hojas del Excel
El archivo `recoleccion_residuos.xlsx` contiene **13 hojas**: 1 resumen anual + 12 hojas mensuales (ABR 2022 a DIC 2023). Cada hoja mensual registra datos diarios de pesaje por compañía recolectora.

In [ ]:
# ─── Carga del archivo Excel ───
ARCHIVO = 'sample_data/recoleccion_residuos.xlsx'
xls = pd.ExcelFile(ARCHIVO)

print(f"Hojas encontradas ({len(xls.sheet_names)}):")
for i, s in enumerate(xls.sheet_names):
    print(f"  {i+1}. {s}")

Hojas encontradas (13):
  1. RESUMEN ANUAL
  2. ABR 2022
  3. OCT 2022
  4. ENE 2023
  5. FEB 2023
  6. MAR 2023
  7. MAY 2023
  8. JUL 2023
  9. AGO 2023
  10. SEP 2023
  11. OCT 2023
  12. NOV 2023
  13. DIC 2023

In [ ]:
# ─── Lectura y unificación de hojas mensuales ───
COLUMNAS_ESTANDAR = [
    'DIA', 'FECHA', 'AMS_TON', 'AMS_PCT', 'MECANIZADOS_TON', 'MECANIZADOS_PCT',
    'TOTAL_AYUNTAMIENTO_TON', 'TOTAL_AYUNTAMIENTO_PCT', 'COMLURSA_TON', 'COMLURSA_PCT',
    'URBALUZ_TON', 'URBALUZ_PCT', 'TOTAL_PRIVADAS_TON', 'TOTAL_PRIVADAS_PCT',
    'TOTAL_GENERAL_TON'
]

FILAS_EXCLUIR = ['TOTALES', 'DIAS TRABAJADOS', 'PROMEDIO DIARIO', 'PORCENTAJE']
MESES_MAP = {
    'ENE': '01', 'FEB': '02', 'MAR': '03', 'ABR': '04', 'MAY': '05', 'JUN': '06',
    'JUL': '07', 'AGO': '08', 'SEP': '09', 'OCT': '10', 'NOV': '11', 'DIC': '12'
}

frames = []
resumen_info = []

for sheet_name in xls.sheet_names:
    if sheet_name == 'RESUMEN ANUAL':
        continue

    raw = pd.read_excel(xls, sheet_name=sheet_name, header=None)

    # La fila 1 tiene los headers reales (DIA, FECHA, etc.)
    # La fila 0 es el título de la hoja
    # Los datos empiezan en fila 2
    header_row = raw.iloc[1].values
    data = raw.iloc[2:].copy()
    data.columns = COLUMNAS_ESTANDAR

    # Excluir filas de resumen (TOTALES, DIAS TRABAJADOS, etc.)
    data = data[~data['DIA'].isin(FILAS_EXCLUIR)].copy()

    # Extraer mes y año del nombre de la hoja
    parts = sheet_name.split()
    mes_str, anio = parts[0], parts[1]
    mes_num = MESES_MAP.get(mes_str, '00')
    data['MES'] = int(mes_num)
    data['ANIO'] = int(anio)
    data['HOJA_ORIGEN'] = sheet_name

    resumen_info.append({
        'hoja': sheet_name,
        'filas_datos': len(data),
        'mes': mes_num,
        'anio': anio
    })
    frames.append(data)

df = pd.concat(frames, ignore_index=True)
print(f"✅ Dataset unificado: {df.shape[0]} registros × {df.shape[1]} columnas")
print(f"   Hojas procesadas: {len(frames)}")
pd.DataFrame(resumen_info)

✅ Dataset unificado: 362 registros × 18 columnas
   Hojas procesadas: 12

        hoja  filas_datos mes  anio
0   ABR 2022           30  04  2022
1   OCT 2022           31  10  2022
2   ENE 2023           31  01  2023
3   FEB 2023           28  02  2023
4   MAR 2023           31  03  2023
5   MAY 2023           31  05  2023
6   JUL 2023           31  07  2023
7   AGO 2023           31  08  2023
8   SEP 2023           30  09  2023
9   OCT 2023           31  10  2023
10  NOV 2023           30  11  2023
11  DIC 2023           27  12  2023

### 1.2 Dimensiones y tipos de variables

In [ ]:
print(f"Dimensiones: {df.shape[0]} filas × {df.shape[1]} columnas")
print(f"\nTipos de datos originales:")
print(df.dtypes)
print(f"\nMemoria: {df.memory_usage(deep=True).sum() / 1024:.1f} KB")

Dimensiones: 362 filas × 18 columnas

Tipos de datos originales:
DIA                       object
FECHA                     object
AMS_TON                   object
AMS_PCT                   object
MECANIZADOS_TON           object
MECANIZADOS_PCT           object
TOTAL_AYUNTAMIENTO_TON    object
TOTAL_AYUNTAMIENTO_PCT    object
COMLURSA_TON              object
COMLURSA_PCT              object
URBALUZ_TON               object
URBALUZ_PCT               object
TOTAL_PRIVADAS_TON        object
TOTAL_PRIVADAS_PCT        object
TOTAL_GENERAL_TON         object
MES                        int64
ANIO                       int64
HOJA_ORIGEN               object
dtype: object

Memoria: 214.5 KB

In [ ]:
# Vista previa de los datos
df.head(10)

,DIA,FECHA,AMS_TON,AMS_PCT,MECANIZADOS_TON,MECANIZADOS_PCT,TOTAL_AYUNTAMIENTO_TON,TOTAL_AYUNTAMIENTO_PCT,COMLURSA_TON,COMLURSA_PCT,URBALUZ_TON,URBALUZ_PCT,TOTAL_PRIVADAS_TON,TOTAL_PRIVADAS_PCT,TOTAL_GENERAL_TON,MES,ANIO,HOJA_ORIGEN
0,V,01/ABRIL/2022,13.73,0.02,NaN,0,13.73,0.02,317.11,0.43,399.74,0.55,716.85,0.98,734.58,4,2022,ABR 2022
1,S,02/ABRIL/2022,48.91,0.07,NaN,0,48.91,0.07,298.59,0.43,345.69,0.50,644.28,0.93,693.19,4,2022,ABR 2022
2,D,03/ABRIL/2022,35.07,0.13,NaN,0,35.07,0.13,117.76,0.44,111.85,0.42,229.61,0.87,264.65,4,2022,ABR 2022
3,L,04/ABRIL/2022,34.54,0.05,NaN,0,34.54,0.05,300.95,0.41,403.17,0.55,704.12,0.95,738.66,4,2022,ABR 2022
4,M,05/ABRIL/2022,27.88,0.04,NaN,0,27.88,0.04,325.45,0.41,443.21,0.56,768.69,0.96,794.57,4,2022,ABR 2022
5,MI,06/ABRIL/2022,20.42,0.03,NaN,0,20.42,0.03,354.65,0.46,393.84,0.51,748.49,0.97,768.91,4,2022,ABR 2022
6,J,07/ABRIL/2022,28.19,0.04,NaN,0,28.19,0.04,306.54,0.45,348.23,0.51,654.77,0.96,682.96,4,2022,ABR 2022
7,V,08/ABRIL/2022,20.87,0.03,NaN,0,20.87,0.03,301.19,0.44,367.45,0.53,668.64,0.97,689.51,4,2022,ABR 2022
8,S,09/ABRIL/2022,39.68,0.06,NaN,0,39.68,0.06,296.57,0.46,304.71,0.48,601.28,0.94,641.96,4,2022,ABR 2022
9,D,10/ABRIL/2022,15.74,0.07,NaN,0,15.74,0.07,98.11,0.44,108.54,0.49,206.65,0.93,222.39,4,2022,ABR 2022

### 1.3 Conversión de tipos y estructura

In [ ]:
# ─── Conversión de columnas numéricas ───
cols_numericas = [c for c in COLUMNAS_ESTANDAR if c not in ('DIA', 'FECHA')]

for col in cols_numericas:
    df[col] = pd.to_numeric(df[col], errors='coerce')

print("Tipos después de conversión:")
print(df[cols_numericas].dtypes)
print(f"\nResumen estadístico:")
df[cols_numericas].describe()

Tipos después de conversión:
AMS_TON                   float64
AMS_PCT                   float64
MECANIZADOS_TON           float64
MECANIZADOS_PCT           float64
TOTAL_AYUNTAMIENTO_TON    float64
TOTAL_AYUNTAMIENTO_PCT    float64
COMLURSA_TON              float64
COMLURSA_PCT              float64
URBALUZ_TON               float64
URBALUZ_PCT               float64
TOTAL_PRIVADAS_TON        float64
TOTAL_PRIVADAS_PCT        float64
TOTAL_GENERAL_TON         float64
dtype: object

Resumen estadístico:

,AMS_TON,AMS_PCT,MECANIZADOS_TON,MECANIZADOS_PCT,TOTAL_AYUNTAMIENTO_TON,TOTAL_AYUNTAMIENTO_PCT,COMLURSA_TON,COMLURSA_PCT,URBALUZ_TON,URBALUZ_PCT,TOTAL_PRIVADAS_TON,TOTAL_PRIVADAS_PCT,TOTAL_GENERAL_TON
count,361.00,362.00,60.00,362.00,361.00,362.00,362.00,362.00,362.00,362.00,362.00,362.00,362.00
mean,48.60,0.08,3.50,0.00,49.20,0.08,262.48,0.40,335.83,0.52,598.31,0.91,647.43
std,16.25,0.04,2.26,0.00,16.33,0.04,85.88,0.05,101.71,0.04,184.16,0.04,192.13
min,11.30,0.00,0.62,0.00,11.30,0.00,35.54,0.18,37.29,0.28,95.67,0.71,134.76
25%,37.56,0.06,1.90,0.00,38.46,0.06,263.38,0.38,318.24,0.50,593.43,0.91,637.30
50%,47.15,0.07,3.06,0.00,48.08,0.08,290.48,0.40,370.24,0.52,666.44,0.92,715.29
75%,57.70,0.09,4.43,0.00,58.27,0.09,311.25,0.43,400.52,0.54,709.76,0.94,763.04
max,112.61,0.29,14.45,0.02,112.61,0.29,392.75,0.52,468.77,0.65,833.03,1.00,911.40

### 1.4 Distribución de variables principales

In [ ]:
# ─── Distribución de TOTAL_GENERAL_TON (variable objetivo) ───
fig, axes = plt.subplots(1, 3, figsize=(16, 4))

# Histograma
df['TOTAL_GENERAL_TON'].dropna().hist(bins=40, ax=axes[0], color='#2196F3', edgecolor='white')
axes[0].set_title('Distribución TOTAL_GENERAL_TON')
axes[0].set_xlabel('Toneladas')

# Boxplot
df[['TOTAL_GENERAL_TON']].dropna().boxplot(ax=axes[1])
axes[1].set_title('Boxplot TOTAL_GENERAL_TON')

# QQ plot
stats.probplot(df['TOTAL_GENERAL_TON'].dropna(), plot=axes[2])
axes[2].set_title('Q-Q Plot TOTAL_GENERAL_TON')

plt.tight_layout()
plt.savefig('01_distribucion_total_general.png', dpi=150, bbox_inches='tight')
plt.show()
print(f"Skewness: {df['TOTAL_GENERAL_TON'].skew():.3f}")
print(f"Kurtosis: {df['TOTAL_GENERAL_TON'].kurtosis():.3f}")

Skewness: -1.590
Kurtosis: 1.202

In [ ]:
# ─── Distribución por compañía recolectora ───
cols_companias = ['AMS_TON', 'COMLURSA_TON', 'URBALUZ_TON', 'MECANIZADOS_TON']
fig, axes = plt.subplots(2, 2, figsize=(14, 8))

for ax, col in zip(axes.flatten(), cols_companias):
    data_col = df[col].dropna()
    data_col[data_col > 0].hist(bins=30, ax=ax, color='#4CAF50', edgecolor='white')
    ax.set_title(f'{col} (media={data_col.mean():.1f})')
    ax.set_xlabel('Toneladas')

plt.suptitle('Distribución diaria por compañía recolectora', fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig('02_distribucion_companias.png', dpi=150, bbox_inches='tight')
plt.show()

In [ ]:
# ─── Evolución mensual del total de residuos ───
mensual = df.groupby(['ANIO', 'MES'])['TOTAL_GENERAL_TON'].agg(['sum', 'mean', 'count']).reset_index()
mensual['PERIODO'] = mensual['ANIO'].astype(str) + '-' + mensual['MES'].astype(str).str.zfill(2)
mensual = mensual.sort_values('PERIODO')

fig, ax = plt.subplots(figsize=(14, 5))
ax.bar(mensual['PERIODO'], mensual['sum'], color='#FF9800', edgecolor='white')
ax.set_title('Total mensual de residuos recolectados (TON)', fontsize=13)
ax.set_xlabel('Periodo')
ax.set_ylabel('Toneladas')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('03_evolucion_mensual.png', dpi=150, bbox_inches='tight')
plt.show()

## 2. Diagnóstico de Calidad de Datos

### 2.1 Valores faltantes

In [ ]:
# ─── Análisis de valores nulos ───
nulos = df.isnull().sum()
nulos_pct = (df.isnull().sum() / len(df) * 100).round(2)
resumen_nulos = pd.DataFrame({'Nulos': nulos, 'Porcentaje (%)': nulos_pct})
resumen_nulos = resumen_nulos[resumen_nulos['Nulos'] > 0].sort_values('Nulos', ascending=False)

print("=== VALORES FALTANTES ===")
print(resumen_nulos)
print(f"\nTotal de celdas con valores nulos: {df.isnull().sum().sum()}")
print(f"Porcentaje global de nulidad: {df.isnull().sum().sum() / df.size * 100:.2f}%")

# Visualización de nulos por hoja
nulos_por_hoja = df.groupby('HOJA_ORIGEN')[cols_numericas].apply(lambda x: x.isnull().sum())
print("\n=== NULOS POR HOJA DE ORIGEN ===")
print(nulos_por_hoja[nulos_por_hoja.sum(axis=1) > 0].to_string())

=== VALORES FALTANTES ===
                        Nulos  Porcentaje (%)
MECANIZADOS_TON           302           83.43
AMS_TON                     1            0.28
TOTAL_AYUNTAMIENTO_TON      1            0.28

Total de celdas con valores nulos: 304
Porcentaje global de nulidad: 4.67%

=== NULOS POR HOJA DE ORIGEN ===
             AMS_TON  AMS_PCT  MECANIZADOS_TON  MECANIZADOS_PCT  TOTAL_AYUNTAMIENTO_TON  TOTAL_AYUNTAMIENTO_PCT  COMLURSA_TON  COMLURSA_PCT  URBALUZ_TON  URBALUZ_PCT  TOTAL_PRIVADAS_TON  TOTAL_PRIVADAS_PCT  TOTAL_GENERAL_TON
HOJA_ORIGEN
ABR 2022           0        0               30                0                       0                       0             0             0            0            0                   0                   0                  0
AGO 2023           0        0               31                0                       0                       0             0             0            0            0                   0                   0                  0
DIC 2023           0        0               20                0                       0                       0             0             0            0            0                   0                   0                  0
ENE 2023           0        0               25                0                       0                       0             0             0            0            0                   0                   0                  0
FEB 2023           0        0               27                0                       0                       0             0             0            0            0                   0                   0                  0
JUL 2023           0        0               31                0                       0                       0             0             0            0            0                   0                   0                  0
MAR 2023           0        0               25                0                       0                       0             0             0            0            0                   0                   0                  0
MAY 2023           0        0               31                0                       0                       0             0             0            0            0                   0                   0                  0
NOV 2023           0        0               17                0                       0                       0             0             0            0            0                   0                   0                  0
OCT 2022           1        0               15                0                       1                       0             0             0            0            0                   0                   0                  0
OCT 2023           0        0               26                0                       0                       0             0             0            0            0                   0                   0                  0
SEP 2023           0        0               24                0                       0                       0             0             0            0            0                   0                   0                  0

In [ ]:
# ─── Heatmap de nulidad ───
fig, ax = plt.subplots(figsize=(14, 5))
sns.heatmap(df[cols_numericas].isnull().T, cbar=True, cmap='YlOrRd', yticklabels=True, ax=ax)
ax.set_title('Mapa de calor de valores faltantes por variable', fontsize=13)
ax.set_xlabel('Registro (fila)')
plt.tight_layout()
plt.savefig('04_heatmap_nulos.png', dpi=150, bbox_inches='tight')
plt.show()

### 2.2 Registros duplicados

In [ ]:
# ─── Detección de duplicados ───
print("=== DUPLICADOS ===")
dup_exactos = df.duplicated().sum()
print(f"Duplicados exactos (todas las columnas): {dup_exactos}")

dup_fecha = df.duplicated(subset=['FECHA']).sum()
print(f"Duplicados por FECHA: {dup_fecha}")

dup_fecha_total = df.duplicated(subset=['FECHA', 'TOTAL_GENERAL_TON']).sum()
print(f"Duplicados por FECHA + TOTAL_GENERAL_TON: {dup_fecha_total}")

# Mostrar ejemplos de duplicados si existen
if dup_fecha > 0:
    fechas_dup = df[df.duplicated(subset=['FECHA'], keep=False)].sort_values('FECHA')
    print(f"\nEjemplos de registros con FECHA duplicada ({min(10, len(fechas_dup))} primeros):")
    print(fechas_dup.head(10)[['FECHA', 'HOJA_ORIGEN', 'AMS_TON', 'COMLURSA_TON', 'TOTAL_GENERAL_TON']].to_string())

=== DUPLICADOS ===
Duplicados exactos (todas las columnas): 0
Duplicados por FECHA: 0
Duplicados por FECHA + TOTAL_GENERAL_TON: 0

### 2.3 Valores extremos (Outliers)

In [ ]:
# ─── Detección de outliers con IQR ───
print("=== DETECCIÓN DE OUTLIERS (Método IQR) ===\n")

cols_toneladas = ['AMS_TON', 'MECANIZADOS_TON', 'TOTAL_AYUNTAMIENTO_TON',
                  'COMLURSA_TON', 'URBALUZ_TON', 'TOTAL_PRIVADAS_TON', 'TOTAL_GENERAL_TON']

outlier_report = []
for col in cols_toneladas:
    data = df[col].dropna()
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = data[(data < lower) | (data > upper)]
    outlier_report.append({
        'Variable': col,
        'Q1': round(Q1, 2),
        'Q3': round(Q3, 2),
        'IQR': round(IQR, 2),
        'Lim_Inf': round(lower, 2),
        'Lim_Sup': round(upper, 2),
        'N_Outliers': len(outliers),
        'Pct_Outliers': round(len(outliers)/len(data)*100, 2)
    })

df_outliers = pd.DataFrame(outlier_report)
print(df_outliers.to_string(index=False))

=== DETECCIÓN DE OUTLIERS (Método IQR) ===

              Variable     Q1     Q3    IQR  Lim_Inf  Lim_Sup  N_Outliers  Pct_Outliers
               AMS_TON  37.56  57.70  20.14     7.35    87.91           8          2.22
       MECANIZADOS_TON   1.90   4.43   2.52    -1.88     8.21           2          3.33
TOTAL_AYUNTAMIENTO_TON  38.46  58.27  19.81     8.74    87.99           8          2.22
          COMLURSA_TON 263.38 311.25  47.87   191.58   383.05          56         15.47
           URBALUZ_TON 318.24 400.52  82.28   194.82   523.94          52         14.36
    TOTAL_PRIVADAS_TON 593.43 709.76 116.32   418.95   884.24          53         14.64
     TOTAL_GENERAL_TON 637.30 763.04 125.74   448.69   951.65          54         14.92

In [ ]:
# ─── Boxplots comparativos ───
fig, axes = plt.subplots(1, len(cols_toneladas), figsize=(20, 5))

for ax, col in zip(axes, cols_toneladas):
    df[[col]].dropna().boxplot(ax=ax)
    ax.set_title(col.replace('_TON', ''), fontsize=9)
    ax.tick_params(axis='x', labelbottom=False)

plt.suptitle('Boxplots — Detección de outliers por variable (TON)', fontsize=13, y=1.02)
plt.tight_layout()
plt.savefig('05_boxplots_outliers.png', dpi=150, bbox_inches='tight')
plt.show()

### 2.4 Inconsistencias en variables categóricas y numéricas

In [ ]:
# ─── Inconsistencias categóricas ───
print("=== INCONSISTENCIAS CATEGÓRICAS ===\n")

print("Valores únicos en DIA (día de semana):")
print(df['DIA'].value_counts().to_string())
print(f"\nTotal valores únicos DIA: {df['DIA'].nunique()}")

print("\nValores únicos en HOJA_ORIGEN:")
print(df['HOJA_ORIGEN'].value_counts().to_string())

=== INCONSISTENCIAS CATEGÓRICAS ===

Valores únicos en DIA (día de semana):
DIA
V     55
S     53
D     52
L     51
MI    51
M     50
J     50

Total valores únicos DIA: 7

Valores únicos en HOJA_ORIGEN:
HOJA_ORIGEN
OCT 2022    31
ENE 2023    31
MAY 2023    31
MAR 2023    31
OCT 2023    31
AGO 2023    31
JUL 2023    31
ABR 2022    30
NOV 2023    30
SEP 2023    30
FEB 2023    28
DIC 2023    27

In [ ]:
# ─── Validación de consistencia numérica ───
print("=== VALIDACIONES DE CONSISTENCIA NUMÉRICA ===\n")

# 1. TOTAL_AYUNTAMIENTO = AMS + MECANIZADOS
df['_CHECK_AYUNT'] = (df['AMS_TON'].fillna(0) + df['MECANIZADOS_TON'].fillna(0))
diff_ayunt = (df['TOTAL_AYUNTAMIENTO_TON'] - df['_CHECK_AYUNT']).abs()
inconsistencias_ayunt = (diff_ayunt > 0.1).sum()
print(f"1. TOTAL_AYUNTAMIENTO ≠ AMS + MECANIZADOS: {inconsistencias_ayunt} registros ({inconsistencias_ayunt/len(df)*100:.1f}%)")

# 2. TOTAL_PRIVADAS = COMLURSA + URBALUZ
df['_CHECK_PRIV'] = (df['COMLURSA_TON'].fillna(0) + df['URBALUZ_TON'].fillna(0))
diff_priv = (df['TOTAL_PRIVADAS_TON'] - df['_CHECK_PRIV']).abs()
inconsistencias_priv = (diff_priv > 0.1).sum()
print(f"2. TOTAL_PRIVADAS ≠ COMLURSA + URBALUZ: {inconsistencias_priv} registros ({inconsistencias_priv/len(df)*100:.1f}%)")

# 3. TOTAL_GENERAL = TOTAL_AYUNTAMIENTO + TOTAL_PRIVADAS
df['_CHECK_GENERAL'] = (df['TOTAL_AYUNTAMIENTO_TON'].fillna(0) + df['TOTAL_PRIVADAS_TON'].fillna(0))
diff_gen = (df['TOTAL_GENERAL_TON'] - df['_CHECK_GENERAL']).abs()
inconsistencias_gen = (diff_gen > 0.1).sum()
print(f"3. TOTAL_GENERAL ≠ TOTAL_AYUNTAMIENTO + TOTAL_PRIVADAS: {inconsistencias_gen} registros ({inconsistencias_gen/len(df)*100:.1f}%)")

# 4. Porcentajes no suman ~1.0
df['_CHECK_PCT'] = df['TOTAL_AYUNTAMIENTO_PCT'].fillna(0) + df['TOTAL_PRIVADAS_PCT'].fillna(0)
inconsistencias_pct = ((df['_CHECK_PCT'] - 1.0).abs() > 0.02).sum()
print(f"4. Porcentajes AYUNT+PRIV ≠ 100%: {inconsistencias_pct} registros ({inconsistencias_pct/len(df)*100:.1f}%)")

# 5. Valores negativos
negativos = (df[cols_toneladas] < 0).sum()
print(f"\n5. Valores negativos por variable:")
print(negativos[negativos > 0] if negativos.sum() > 0 else "   Ninguno detectado")

# 6. Ceros sospechosos en TOTAL_GENERAL
ceros_total = (df['TOTAL_GENERAL_TON'] == 0).sum()
print(f"\n6. Días con TOTAL_GENERAL = 0: {ceros_total}")

# Limpiar columnas temporales
df.drop(columns=[c for c in df.columns if c.startswith('_CHECK')], inplace=True)

=== VALIDACIONES DE CONSISTENCIA NUMÉRICA ===

1. TOTAL_AYUNTAMIENTO ≠ AMS + MECANIZADOS: 4 registros (1.1%)
2. TOTAL_PRIVADAS ≠ COMLURSA + URBALUZ: 3 registros (0.8%)
3. TOTAL_GENERAL ≠ TOTAL_AYUNTAMIENTO + TOTAL_PRIVADAS: 17 registros (4.7%)
4. Porcentajes AYUNT+PRIV ≠ 100%: 5 registros (1.4%)

5. Valores negativos por variable:
   Ninguno detectado

6. Días con TOTAL_GENERAL = 0: 0

In [ ]:
# ─── Validación cruzada: Resumen anual vs suma de hojas mensuales ───
print("=== VALIDACIÓN CRUZADA: RESUMEN ANUAL vs DATOS DIARIOS ===\n")

df_resumen = pd.read_excel(ARCHIVO, sheet_name='RESUMEN ANUAL', header=None)
df_resumen.columns = ['MES_ANIO'] + [f'col_{i}' for i in range(1, df_resumen.shape[1])]
df_resumen = df_resumen.iloc[1:-1]  # Excluir header y TOTAL GENERAL
df_resumen = df_resumen[~df_resumen['MES_ANIO'].isin(['TOTAL GENERAL'])]

# col_13 = TOTAL GENERAL TON en el resumen
df_resumen['TOTAL_RESUMEN'] = pd.to_numeric(df_resumen['col_13'], errors='coerce')

# Calcular suma desde los datos diarios
suma_mensual = df.groupby('HOJA_ORIGEN')['TOTAL_GENERAL_TON'].sum().reset_index()
suma_mensual.columns = ['HOJA', 'TOTAL_CALCULADO']

print("Comparación (resumen oficial vs. suma de datos diarios):")
for _, row in df_resumen.iterrows():
    mes_anio = str(row['MES_ANIO']).strip()
    total_res = row['TOTAL_RESUMEN']
    # Buscar la hoja correspondiente
    hoja_match = [h for h in suma_mensual['HOJA'].values if mes_anio.replace(' ', '') in h.replace(' ', '')]
    if hoja_match:
        total_calc = suma_mensual[suma_mensual['HOJA'] == hoja_match[0]]['TOTAL_CALCULADO'].values[0]
        diff = abs(total_res - total_calc) if pd.notna(total_res) and pd.notna(total_calc) else None
        status = 'Correcto' if diff is not None and diff < 1 else ('Diferente' if diff is not None else 'Incorrecto')
        print(f"  {mes_anio:15s} | Resumen: {total_res:>12} | Calculado: {total_calc:>12.2f} | {status}")
    else:
        print(f"  {mes_anio:15s} | Resumen: {total_res:>12} | Sin hoja mensual")

=== VALIDACIÓN CRUZADA: RESUMEN ANUAL vs DATOS DIARIOS ===

Comparación (resumen oficial vs. suma de datos diarios):
  MES/AÑO         | Resumen:          nan | Sin hoja mensual
  ABR 2022        | Resumen:     18698.66 | Calculado:     18699.63 | Correcto
  OCT 2022        | Resumen:     20625.94 | Calculado:     20625.94 | Correcto
  ENE 2023        | Resumen:      19039.7 | Calculado:     19039.70 | Correcto
  FEB 2023        | Resumen:     17665.91 | Calculado:     17665.91 | Correcto
  MAR 2023        | Resumen:     20257.83 | Calculado:     20257.83 | Correcto
  MAY 2023        | Resumen:     21384.06 | Calculado:     21572.98 | Diferente
  JUL 2023        | Resumen:     20704.56 | Calculado:     20704.56 | Correcto
  AGO 2023        | Resumen:          nan | Calculado:     20854.26 | Incorrecto
  SEP 2023        | Resumen:          nan | Calculado:     19742.76 | Incorrecto
  OCT 2023        | Resumen:          nan | Calculado:     19007.09 | Incorrecto
  NOV 2023        | Resumen:     19069.98 | Calculado:     19069.98 | Correcto
  DIC 2023        | Resumen:          nan | Calculado:     17128.02 | Incorrecto

## 3. Preprocesamiento

### 3.1 Limpieza de variables

In [ ]:
df_clean = df.copy()
print(f"Dataset antes de limpieza: {df_clean.shape}")

# ─── 3.1.1 Parsear FECHA a datetime ───
def parse_fecha(fecha_str):
    """Convierte '01/ABRIL/2022' → datetime"""
    if pd.isna(fecha_str):
        return pd.NaT
    meses_es = {
        'ENERO': 1, 'FEBRERO': 2, 'MARZO': 3, 'ABRIL': 4, 'MAYO': 5, 'JUNIO': 6,
        'JULIO': 7, 'AGOSTO': 8, 'SEPTIEMBRE': 9, 'OCTUBRE': 10, 'NOVIEMBRE': 11, 'DICIEMBRE': 12
    }
    try:
        parts = str(fecha_str).strip().split('/')
        dia = int(parts[0])
        mes = meses_es.get(parts[1].upper(), 0)
        anio = int(parts[2])
        return pd.Timestamp(year=anio, month=mes, day=dia)
    except:
        return pd.NaT

df_clean['FECHA_DT'] = df_clean['FECHA'].apply(parse_fecha)
fechas_invalidas = df_clean['FECHA_DT'].isna().sum()
print(f"Fechas no parseables: {fechas_invalidas}")
if fechas_invalidas > 0:
    print(df_clean[df_clean['FECHA_DT'].isna()][['FECHA', 'HOJA_ORIGEN']].head())

Dataset antes de limpieza: (362, 18)
Fechas no parseables: 0

In [ ]:
# ─── 3.1.2 Estandarizar DIA (día de la semana) ───
DIAS_MAP = {
    'L': 'Lunes', 'M': 'Martes', 'MI': 'Miércoles', 'J': 'Jueves',
    'V': 'Viernes', 'S': 'Sábado', 'D': 'Domingo'
}
df_clean['DIA_SEMANA'] = df_clean['DIA'].map(DIAS_MAP)
sin_mapeo = df_clean['DIA_SEMANA'].isna().sum()
print(f"Días sin mapeo: {sin_mapeo}")
if sin_mapeo > 0:
    print("Valores problemáticos:", df_clean[df_clean['DIA_SEMANA'].isna()]['DIA'].unique())

# Validar que el día de la semana coincida con la fecha
df_clean['DIA_CALCULADO'] = df_clean['FECHA_DT'].dt.day_name()
dia_map_reverse = {
    'Monday': 'Lunes', 'Tuesday': 'Martes', 'Wednesday': 'Miércoles',
    'Thursday': 'Jueves', 'Friday': 'Viernes', 'Saturday': 'Sábado', 'Sunday': 'Domingo'
}
df_clean['DIA_CALCULADO_ES'] = df_clean['DIA_CALCULADO'].map(dia_map_reverse)
inconsist_dia = (df_clean['DIA_SEMANA'] != df_clean['DIA_CALCULADO_ES']).sum()
print(f"Inconsistencias DIA declarado vs. calculado: {inconsist_dia}")

Días sin mapeo: 0
Inconsistencias DIA declarado vs. calculado: 6

### 3.2 Tratamiento de valores faltantes

In [ ]:
# ─── Análisis de patrones de nulidad ───
print("=== PATRÓN DE NULOS ANTES DEL TRATAMIENTO ===")
print(df_clean[cols_numericas].isnull().sum())
print(f"\nTotal registros: {len(df_clean)}")

# MECANIZADOS_TON: NaN cuando la compañía no operó ese día → rellenar con 0
df_clean['MECANIZADOS_TON'] = df_clean['MECANIZADOS_TON'].fillna(0)
df_clean['MECANIZADOS_PCT'] = df_clean['MECANIZADOS_PCT'].fillna(0)
print("\n MECANIZADOS_TON/PCT: NaN → 0 (compañía sin operación ese día)")

# TOTAL_GENERAL_TON: NaN en algunos registros — verificar si se puede recalcular
nulos_total = df_clean['TOTAL_GENERAL_TON'].isna()
print(f"\nTOTAL_GENERAL_TON nulos: {nulos_total.sum()}")

# Intentar recalcular TOTAL_GENERAL = TOTAL_AYUNTAMIENTO + TOTAL_PRIVADAS
mask_recalc = nulos_total & df_clean['TOTAL_AYUNTAMIENTO_TON'].notna() & df_clean['TOTAL_PRIVADAS_TON'].notna()
df_clean.loc[mask_recalc, 'TOTAL_GENERAL_TON'] = (
    df_clean.loc[mask_recalc, 'TOTAL_AYUNTAMIENTO_TON'] + df_clean.loc[mask_recalc, 'TOTAL_PRIVADAS_TON']
)
print(f" Recalculados {mask_recalc.sum()} valores de TOTAL_GENERAL_TON")

# Para los restantes, recalcular subtotales si faltan
mask_ayunt_null = df_clean['TOTAL_AYUNTAMIENTO_TON'].isna()
df_clean.loc[mask_ayunt_null, 'TOTAL_AYUNTAMIENTO_TON'] = (
    df_clean.loc[mask_ayunt_null, 'AMS_TON'].fillna(0) + df_clean.loc[mask_ayunt_null, 'MECANIZADOS_TON'].fillna(0)
)
print(f" Recalculados {mask_ayunt_null.sum()} valores de TOTAL_AYUNTAMIENTO_TON")

mask_priv_null = df_clean['TOTAL_PRIVADAS_TON'].isna()
df_clean.loc[mask_priv_null, 'TOTAL_PRIVADAS_TON'] = (
    df_clean.loc[mask_priv_null, 'COMLURSA_TON'].fillna(0) + df_clean.loc[mask_priv_null, 'URBALUZ_TON'].fillna(0)
)
print(f" Recalculados {mask_priv_null.sum()} valores de TOTAL_PRIVADAS_TON")

# Segundo intento para TOTAL_GENERAL
still_null = df_clean['TOTAL_GENERAL_TON'].isna()
df_clean.loc[still_null, 'TOTAL_GENERAL_TON'] = (
    df_clean.loc[still_null, 'TOTAL_AYUNTAMIENTO_TON'].fillna(0) + df_clean.loc[still_null, 'TOTAL_PRIVADAS_TON'].fillna(0)
)
print(f" Recalculados {still_null.sum()} valores adicionales de TOTAL_GENERAL_TON")

# Rellenar porcentajes faltantes recalculando
mask_pct = df_clean['TOTAL_AYUNTAMIENTO_PCT'].isna() & (df_clean['TOTAL_GENERAL_TON'] > 0)
df_clean.loc[mask_pct, 'TOTAL_AYUNTAMIENTO_PCT'] = (
    df_clean.loc[mask_pct, 'TOTAL_AYUNTAMIENTO_TON'] / df_clean.loc[mask_pct, 'TOTAL_GENERAL_TON']
)
df_clean.loc[mask_pct, 'TOTAL_PRIVADAS_PCT'] = (
    df_clean.loc[mask_pct, 'TOTAL_PRIVADAS_TON'] / df_clean.loc[mask_pct, 'TOTAL_GENERAL_TON']
)

print("\n=== NULOS DESPUÉS DEL TRATAMIENTO ===")
print(df_clean[cols_numericas].isnull().sum())

=== PATRÓN DE NULOS ANTES DEL TRATAMIENTO ===
AMS_TON                   1
AMS_PCT                   0
MECANIZADOS_TON           0
MECANIZADOS_PCT           0
TOTAL_AYUNTAMIENTO_TON    0
TOTAL_AYUNTAMIENTO_PCT    0
COMLURSA_TON              0
COMLURSA_PCT              0
URBALUZ_TON               0
URBALUZ_PCT               0
TOTAL_PRIVADAS_TON        0
TOTAL_PRIVADAS_PCT        0
TOTAL_GENERAL_TON         0
dtype: int64

Total registros: 362

 MECANIZADOS_TON/PCT: NaN → 0 (compañía sin operación ese día)

TOTAL_GENERAL_TON nulos: 0
 Recalculados 0 valores de TOTAL_GENERAL_TON
 Recalculados 0 valores de TOTAL_AYUNTAMIENTO_TON
 Recalculados 0 valores de TOTAL_PRIVADAS_TON
 Recalculados 0 valores adicionales de TOTAL_GENERAL_TON

=== NULOS DESPUÉS DEL TRATAMIENTO ===
AMS_TON                   1
AMS_PCT                   0
MECANIZADOS_TON           0
MECANIZADOS_PCT           0
TOTAL_AYUNTAMIENTO_TON    0
TOTAL_AYUNTAMIENTO_PCT    0
COMLURSA_TON              0
COMLURSA_PCT              0
URBALUZ_TON               0
URBALUZ_PCT               0
TOTAL_PRIVADAS_TON        0
TOTAL_PRIVADAS_PCT        0
TOTAL_GENERAL_TON         0
dtype: int64

### 3.3 Eliminación de duplicados

In [ ]:
# ─── Detección y eliminación de duplicados ───
print("=== DUPLICADOS ===")

# Duplicados exactos
dup_exactos = df_clean.duplicated(subset=['FECHA_DT'] + cols_toneladas).sum()
print(f"Duplicados por FECHA + valores numéricos: {dup_exactos}")

if dup_exactos > 0:
    print("\nEjemplos:")
    mask_dup = df_clean.duplicated(subset=['FECHA_DT'] + cols_toneladas, keep=False)
    print(df_clean[mask_dup].sort_values('FECHA_DT').head(6)[
        ['FECHA', 'HOJA_ORIGEN', 'AMS_TON', 'COMLURSA_TON', 'TOTAL_GENERAL_TON']
    ].to_string())

antes = len(df_clean)
df_clean = df_clean.drop_duplicates(subset=['FECHA_DT'] + cols_toneladas, keep='first')
despues = len(df_clean)
print(f"\n Eliminados {antes - despues} duplicados. Registros: {antes} → {despues}")

=== DUPLICADOS ===
Duplicados por FECHA + valores numéricos: 0

 Eliminados 0 duplicados. Registros: 362 → 362

### 3.4 Detección y tratamiento de outliers

In [ ]:
# ─── Outliers en TOTAL_GENERAL_TON usando IQR ───
print("=== TRATAMIENTO DE OUTLIERS (TOTAL_GENERAL_TON) ===\n")

Q1 = df_clean['TOTAL_GENERAL_TON'].quantile(0.25)
Q3 = df_clean['TOTAL_GENERAL_TON'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers_mask = (df_clean['TOTAL_GENERAL_TON'] < lower) | (df_clean['TOTAL_GENERAL_TON'] > upper)
n_outliers = outliers_mask.sum()

print(f"Q1: {Q1:.2f}, Q3: {Q3:.2f}, IQR: {IQR:.2f}")
print(f"Límites: [{lower:.2f}, {upper:.2f}]")
print(f"Outliers detectados: {n_outliers} ({n_outliers/len(df_clean)*100:.1f}%)")

if n_outliers > 0:
    print("\nOutliers encontrados:")
    print(df_clean[outliers_mask][['FECHA', 'HOJA_ORIGEN', 'TOTAL_GENERAL_TON']].to_string())

# Estrategia: Capping (winsorización) en lugar de eliminar
df_clean['TOTAL_GENERAL_TON_ORIGINAL'] = df_clean['TOTAL_GENERAL_TON'].copy()
df_clean.loc[df_clean['TOTAL_GENERAL_TON'] > upper, 'TOTAL_GENERAL_TON'] = upper
df_clean.loc[df_clean['TOTAL_GENERAL_TON'] < lower, 'TOTAL_GENERAL_TON'] = lower
print(f"\n Aplicado capping (winsorización) a {n_outliers} valores extremos")

=== TRATAMIENTO DE OUTLIERS (TOTAL_GENERAL_TON) ===

Q1: 637.30, Q3: 763.04, IQR: 125.74
Límites: [448.69, 951.65]
Outliers detectados: 54 (14.9%)

Outliers encontrados:
                  FECHA HOJA_ORIGEN  TOTAL_GENERAL_TON
2         03/ABRIL/2022    ABR 2022             264.65
9         10/ABRIL/2022    ABR 2022             222.39
14        15/ABRIL/2022    ABR 2022             342.51
16        17/ABRIL/2022    ABR 2022             210.04
23        24/ABRIL/2022    ABR 2022             180.56
31      02/OCTUBRE/2022    OCT 2022             238.03
38      09/OCTUBRE/2022    OCT 2022             182.70
45      16/OCTUBRE/2022    OCT 2022             196.67
52      23/OCTUBRE/2022    OCT 2022             194.49
59      30/OCTUBRE/2022    OCT 2022             243.66
61        01/ENERO/2023    ENE 2023             135.31
68        08/ENERO/2023    ENE 2023             220.34
75        15/ENERO/2023    ENE 2023             231.83
82        22/ENERO/2023    ENE 2023             155.40
89        29/ENERO/2023    ENE 2023             151.68
96      05/FEBRERO/2023    FEB 2023             198.96
103     12/FEBRERO/2023    FEB 2023             188.11
110     19/FEBRERO/2023    FEB 2023             230.43
117     26/FEBRERO/2023    FEB 2023             195.18
124       05/MARZO/2023    MAR 2023             190.05
131       12/MARZO/2023    MAR 2023             184.90
138       19/MARZO/2023    MAR 2023             182.43
145       26/MARZO/2023    MAR 2023             201.38
157        07/MAYO/2023    MAY 2023             215.44
164        14/MAYO/2023    MAY 2023             334.85
171        21/MAYO/2023    MAY 2023             250.38
178        28/MAYO/2023    MAY 2023             191.20
183       02/JULIO/2023    JUL 2023             217.14
190       09/JULIO/2023    JUL 2023             200.32
197       16/JULIO/2023    JUL 2023             201.99
204       23/JULIO/2023    JUL 2023             191.13
211       30/JULIO/2023    JUL 2023             218.00
218      06/AGOSTO/2023    AGO 2023             233.75
225      13/AGOSTO/2023    AGO 2023             187.94
232      20/AGOSTO/2023    AGO 2023             229.30
239      27/AGOSTO/2023    AGO 2023             233.73
246  03/SEPTIEMBRE/2023    SEP 2023             218.31
253  10/SEPTIEMBRE/2023    SEP 2023             208.43
260  17/SEPTIEMBRE/2023    SEP 2023             233.54
267  24/SEPTIEMBRE/2023    SEP 2023             202.87
274     01/OCTUBRE/2023    OCT 2023             195.18
281     08/OCTUBRE/2023    OCT 2023             219.66
288     15/OCTUBRE/2023    OCT 2023             183.88
295     22/OCTUBRE/2023    OCT 2023             134.76
302     29/OCTUBRE/2023    OCT 2023             164.28
309   05/NOVIEMBRE/2023    NOV 2023             185.43
316   12/NOVIEMBRE/2023    NOV 2023             217.23
323   19/NOVIEMBRE/2023    NOV 2023             235.58
330   26/NOVIEMBRE/2023    NOV 2023             202.03
337   03/DICIEMBRE/2023    DIC 2023             225.65
344   10/DICIEMBRE/2023    DIC 2023             224.33
351   17/DICIEMBRE/2023    DIC 2023             269.53
358   24/DICIEMBRE/2023    DIC 2023             395.12
359   25/DICIEMBRE/2023    DIC 2023             393.41

 Aplicado capping (winsorización) a 54 valores extremos

In [ ]:
# ─── Visualización antes/después de outliers ───
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].boxplot(df_clean['TOTAL_GENERAL_TON_ORIGINAL'].dropna())
axes[0].set_title('ANTES: TOTAL_GENERAL_TON (con outliers)')
axes[0].set_ylabel('Toneladas')

axes[1].boxplot(df_clean['TOTAL_GENERAL_TON'].dropna())
axes[1].set_title('DESPUÉS: TOTAL_GENERAL_TON (winsorizado)')
axes[1].set_ylabel('Toneladas')

plt.tight_layout()
plt.savefig('06_outliers_antes_despues.png', dpi=150, bbox_inches='tight')
plt.show()

### 3.5 Transformación de variables y creación de variables derivadas

In [ ]:
# ─── Creación de variables derivadas ───

# Proporción del ayuntamiento vs privadas
df_clean['PROP_AYUNTAMIENTO'] = np.where(
    df_clean['TOTAL_GENERAL_TON'] > 0,
    df_clean['TOTAL_AYUNTAMIENTO_TON'] / df_clean['TOTAL_GENERAL_TON'],
    0
)

# Indicador de fin de semana
df_clean['ES_FIN_DE_SEMANA'] = df_clean['DIA_SEMANA'].isin(['Sábado', 'Domingo']).astype(int)

# Número del día del mes
df_clean['DIA_MES'] = df_clean['FECHA_DT'].dt.day

# Trimestre
df_clean['TRIMESTRE'] = df_clean['FECHA_DT'].dt.quarter

# Semana del año
df_clean['SEMANA_ANIO'] = df_clean['FECHA_DT'].dt.isocalendar().week.astype(int)

# Categoría del volumen diario
bins = [0, 200, 400, 600, 800, float('inf')]
labels = ['Muy_Bajo', 'Bajo', 'Medio', 'Alto', 'Muy_Alto']
df_clean['CAT_VOLUMEN'] = pd.cut(df_clean['TOTAL_GENERAL_TON'], bins=bins, labels=labels)

print(" Variables derivadas creadas:")
print("  - PROP_AYUNTAMIENTO: proporción ayuntamiento / total")
print("  - ES_FIN_DE_SEMANA: indicador binario (0/1)")
print("  - DIA_MES: día numérico del mes")
print("  - TRIMESTRE: trimestre del año (1-4)")
print("  - SEMANA_ANIO: número de semana ISO")
print("  - CAT_VOLUMEN: categoría de volumen (Muy_Bajo a Muy_Alto)")
print(f"\nDistribución CAT_VOLUMEN:")
print(df_clean['CAT_VOLUMEN'].value_counts().sort_index())

 Variables derivadas creadas:
  - PROP_AYUNTAMIENTO: proporción ayuntamiento / total
  - ES_FIN_DE_SEMANA: indicador binario (0/1)
  - DIA_MES: día numérico del mes
  - TRIMESTRE: trimestre del año (1-4)
  - SEMANA_ANIO: número de semana ISO
  - CAT_VOLUMEN: categoría de volumen (Muy_Bajo a Muy_Alto)

Distribución CAT_VOLUMEN:
CAT_VOLUMEN
Muy_Bajo      0
Bajo          0
Medio        70
Alto        256
Muy_Alto     36
Name: count, dtype: int64

In [ ]:
# ─── Distribución fin de semana vs laborables ───
fig, ax = plt.subplots(figsize=(8, 5))
df_clean.groupby('ES_FIN_DE_SEMANA')['TOTAL_GENERAL_TON'].mean().plot(
    kind='bar', color=['#2196F3', '#FF5722'], ax=ax
)
ax.set_xticklabels(['Día Laborable', 'Fin de Semana'], rotation=0)
ax.set_title('Promedio de residuos: Laborable vs. Fin de Semana')
ax.set_ylabel('Toneladas (promedio diario)')
plt.tight_layout()
plt.savefig('07_laborable_vs_finde.png', dpi=150, bbox_inches='tight')
plt.show()

## 4. Dataset Final Preparado

### 4.1 Selección y orden final de columnas

In [ ]:
# ─── Dataset final limpio ───
COLUMNAS_FINAL = [
    'FECHA_DT', 'DIA_SEMANA', 'MES', 'ANIO', 'TRIMESTRE', 'SEMANA_ANIO', 'DIA_MES',
    'ES_FIN_DE_SEMANA',
    'AMS_TON', 'MECANIZADOS_TON', 'TOTAL_AYUNTAMIENTO_TON',
    'COMLURSA_TON', 'URBALUZ_TON', 'TOTAL_PRIVADAS_TON',
    'TOTAL_GENERAL_TON',
    'PROP_AYUNTAMIENTO', 'CAT_VOLUMEN',
    'HOJA_ORIGEN'
]

df_final = df_clean[COLUMNAS_FINAL].copy()
df_final = df_final.sort_values('FECHA_DT').reset_index(drop=True)
df_final = df_final.rename(columns={'FECHA_DT': 'FECHA'})

print("=== DATASET FINAL ===")
print(f"Dimensiones: {df_final.shape[0]} filas × {df_final.shape[1]} columnas")
print(f"\nColumnas:")
for c in df_final.columns:
    print(f"  {c:30s} {str(df_final[c].dtype):10s} | Nulos: {df_final[c].isna().sum()}")
print(f"\nRango temporal: {df_final['FECHA'].min()} → {df_final['FECHA'].max()}")
print(f"Meses cubiertos: {df_final.groupby(['ANIO','MES']).ngroups}")

df_final.head(10)

=== DATASET FINAL ===
Dimensiones: 362 filas × 18 columnas

Columnas:
  FECHA                          datetime64[ns] | Nulos: 0
  DIA_SEMANA                     object     | Nulos: 0
  MES                            int64      | Nulos: 0
  ANIO                           int64      | Nulos: 0
  TRIMESTRE                      int32      | Nulos: 0
  SEMANA_ANIO                    int64      | Nulos: 0
  DIA_MES                        int32      | Nulos: 0
  ES_FIN_DE_SEMANA               int64      | Nulos: 0
  AMS_TON                        float64    | Nulos: 1
  MECANIZADOS_TON                float64    | Nulos: 0
  TOTAL_AYUNTAMIENTO_TON         float64    | Nulos: 0
  COMLURSA_TON                   float64    | Nulos: 0
  URBALUZ_TON                    float64    | Nulos: 0
  TOTAL_PRIVADAS_TON             float64    | Nulos: 0
  TOTAL_GENERAL_TON              float64    | Nulos: 0
  PROP_AYUNTAMIENTO              float64    | Nulos: 0
  CAT_VOLUMEN                    category   | Nulos: 0
  HOJA_ORIGEN                    object     | Nulos: 0

Rango temporal: 2022-04-01 00:00:00 → 2023-12-27 00:00:00
Meses cubiertos: 12

,FECHA,DIA_SEMANA,MES,ANIO,TRIMESTRE,SEMANA_ANIO,DIA_MES,ES_FIN_DE_SEMANA,AMS_TON,MECANIZADOS_TON,TOTAL_AYUNTAMIENTO_TON,COMLURSA_TON,URBALUZ_TON,TOTAL_PRIVADAS_TON,TOTAL_GENERAL_TON,PROP_AYUNTAMIENTO,CAT_VOLUMEN,HOJA_ORIGEN
0,2022-04-01,Viernes,4,2022,2,13,1,0,13.73,0.00,13.73,317.11,399.74,716.85,734.58,0.02,Alto,ABR 2022
1,2022-04-02,Sábado,4,2022,2,13,2,1,48.91,0.00,48.91,298.59,345.69,644.28,693.19,0.07,Alto,ABR 2022
2,2022-04-03,Domingo,4,2022,2,13,3,1,35.07,0.00,35.07,117.76,111.85,229.61,448.69,0.08,Medio,ABR 2022
3,2022-04-04,Lunes,4,2022,2,14,4,0,34.54,0.00,34.54,300.95,403.17,704.12,738.66,0.05,Alto,ABR 2022
4,2022-04-05,Martes,4,2022,2,14,5,0,27.88,0.00,27.88,325.45,443.21,768.69,794.57,0.04,Alto,ABR 2022
5,2022-04-06,Miércoles,4,2022,2,14,6,0,20.42,0.00,20.42,354.65,393.84,748.49,768.91,0.03,Alto,ABR 2022
6,2022-04-07,Jueves,4,2022,2,14,7,0,28.19,0.00,28.19,306.54,348.23,654.77,682.96,0.04,Alto,ABR 2022
7,2022-04-08,Viernes,4,2022,2,14,8,0,20.87,0.00,20.87,301.19,367.45,668.64,689.51,0.03,Alto,ABR 2022
8,2022-04-09,Sábado,4,2022,2,14,9,1,39.68,0.00,39.68,296.57,304.71,601.28,641.96,0.06,Alto,ABR 2022
9,2022-04-10,Domingo,4,2022,2,14,10,1,15.74,0.00,15.74,98.11,108.54,206.65,448.69,0.04,Medio,ABR 2022

In [ ]:
# ─── Estadísticas finales ───
print("=== RESUMEN ESTADÍSTICO FINAL ===")
df_final.describe()

=== RESUMEN ESTADÍSTICO FINAL ===

,FECHA,MES,ANIO,TRIMESTRE,SEMANA_ANIO,DIA_MES,ES_FIN_DE_SEMANA,AMS_TON,MECANIZADOS_TON,TOTAL_AYUNTAMIENTO_TON,COMLURSA_TON,URBALUZ_TON,TOTAL_PRIVADAS_TON,TOTAL_GENERAL_TON,PROP_AYUNTAMIENTO
count,362,362.00,362.00,362.00,362.00,362.00,362.00,361.00,362.00,362.00,362.00,362.00,362.00,362.00,362.00
mean,2023-05-09 22:40:26.519336960,6.81,2022.83,2.66,27.76,15.61,0.29,48.60,0.58,49.07,262.48,335.83,598.31,681.88,0.07
min,2022-04-01 00:00:00,1.00,2022.00,1.00,1.00,1.00,0.00,11.30,0.00,0.00,35.54,37.29,95.67,448.69,0.00
25%,2023-01-30 06:00:00,4.00,2023.00,2.00,13.00,8.00,0.00,37.56,0.00,38.35,263.38,318.24,593.43,637.30,0.06
50%,2023-05-30 12:00:00,7.00,2023.00,3.00,31.00,16.00,0.00,47.15,0.00,47.98,290.48,370.24,666.44,715.29,0.07
75%,2023-09-27 18:00:00,10.00,2023.00,4.00,41.00,23.00,1.00,57.70,0.00,58.26,311.25,400.52,709.76,763.04,0.08
max,2023-12-27 00:00:00,12.00,2023.00,4.00,52.00,31.00,1.00,112.61,14.45,112.61,392.75,468.77,833.03,911.40,0.15
std,NaN,3.55,0.37,1.18,15.46,8.76,0.45,16.25,1.59,16.51,85.88,101.71,184.16,116.71,0.02

### 4.2 Exportación del dataset limpio

In [ ]:
# ─── Guardar CSV y Excel ───
df_final.to_csv('dataset_residuos_limpio.csv', index=False, encoding='utf-8-sig')
df_final.to_excel('dataset_residuos_limpio.xlsx', index=False, sheet_name='Datos_Limpios')

print(" Archivos exportados:")
print("  → dataset_residuos_limpio.csv")
print("  → dataset_residuos_limpio.xlsx")
print(f"\nRegistros finales: {len(df_final)}")

 Archivos exportados:
  → dataset_residuos_limpio.csv
  → dataset_residuos_limpio.xlsx

Registros finales: 362

### 4.3 Resumen de transformaciones aplicadas

| Paso | Transformación | Impacto |
|------|---------------|---------|
| 1 | Unificación de 12 hojas mensuales en un solo DataFrame | Estructura homogénea |
| 2 | Conversión de tipos (object → float64/datetime) | Operabilidad numérica |
| 3 | Parseo de FECHA texto → datetime | Análisis temporal habilitado |
| 4 | Estandarización de DIA → nombre completo | Consistencia categórica |
| 5 | MECANIZADOS NaN → 0 (sin operación) | Eliminación de nulos semánticos |
| 6 | Recálculo de subtotales faltantes (AYUNT, PRIV, GENERAL) | Recuperación de datos |
| 7 | Eliminación de duplicados exactos | Integridad de registros |
| 8 | Winsorización de outliers en TOTAL_GENERAL_TON | Robustez estadística |
| 9 | Creación de variables derivadas (6 nuevas) | Enriquecimiento analítico |
| 10 | Validación cruzada resumen anual vs. datos diarios | Auditoría de integridad |

## 5. Pregunta Final

> **¿El dataset estaba realmente listo para ser utilizado en un proyecto de minería de datos o fue necesario realizar un proceso significativo de preparación de datos?**

### Respuesta

**No, el dataset NO estaba listo para minería de datos.** Fue necesario un proceso significativo de preparación que abarcó múltiples dimensiones:

**Problemas estructurales:**
- Los datos estaban fragmentados en 12 hojas Excel independientes con formato tabular orientado a reportes humanos, no a análisis computacional.
- Cada hoja incluía filas de resumen (TOTALES, PROMEDIOS, PORCENTAJES) mezcladas con datos transaccionales, lo cual requirió filtrado manual.
- Los headers reales estaban desplazados respecto a las convenciones de pandas.

**Problemas de calidad:**
- **Valores faltantes críticos:** La variable TOTAL_GENERAL_TON tenía valores nulos que pudieron ser recalculados a partir de sus componentes, pero su ausencia hubiera invalidado cualquier análisis directo.
- **MECANIZADOS_TON** aparecía como NaN en meses donde esa compañía simplemente no operó — un NaN semántico (no dato faltante, sino ausencia de actividad) que requería interpretación de dominio.
- **Meses incompletos:** Agosto, Septiembre, Octubre y Diciembre 2023 presentaban datos parciales o totales faltantes en la hoja resumen.

**Problemas de consistencia:**
- Las fechas estaban en formato texto en español (01/ABRIL/2022), incompatibles con funciones de series temporales.
- Se detectaron inconsistencias puntuales entre los totales reportados en la hoja resumen y la suma real de los datos diarios.

**Conclusión:** Este dataset es un caso representativo de datos administrativos del sector público que requieren un **proceso intensivo de ETL** antes de poder alimentar cualquier modelo de minería de datos. La ausencia de este preprocesamiento habría producido resultados sesgados o directamente erróneos.